### ISSUE TITLE
github actions stop

### ISSUE THREAD

**Issue by ricoderks** [ndcn/omicser#182]
The github actions are not fnishing. They stop on the error the that package `ComplexHeatmap` can not be installed due to depency `circlize`.

I tried to install `ComplexHeatmap` (via github) locally to see if I can get some more information on the error. The error I get locally is:

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘circlize’ 0.4.13 is being loaded, but >= 0.4.14 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
```

**Comment by ricoderks** [comment]
I noticed that there was a change in `ComplexHeatmap` 6 days ago which causes this. The requirement for `circlize` changed from 0.4.5 to 0.4.14.

**Comment by ergonyc** [comment]
I started looking into this when it first failed. For now waiting to see if there's a CRAN update.   Having the error in the actions is not critical since we don't have updated documentation being pushed... In the longer term I think we may want to pin ComplexHeatmap to a stable version.

Also probably should open an issue / dialog with @jokergoo for advice.  He maintains both ComplexHeatmap and Circlize... and might have some interest in what we are doing.

**Comment by jokergoo** [comment]
Hi, I will submit circlize 0.4.14 to CRAN today :)

**Comment by jokergoo** [comment]
Now 0.4.14  is on CRAN https://cran.r-project.org/web/packages/circlize/index.html
It may take several days to be available on other mirrors.

**Comment by ricoderks** [comment]
Should be fixed know.
